### ISSUE TITLE
Roadmap for Strs.jl

### ISSUE THREAD

**Issue by ScottPJones** [JuliaString/Strs.jl#97]
- [ ] Add built-in SubStr support
- [ ] Add hashed string support
- [ ] Write PCRE2.jl package using BinaryBuilder/BinaryProvider, creating all 3 PCRE2 libraries
- [ ] Move regex support to StrRegex package
- [ ] Change the ranges returned to end with the next codeunit index - 1, not need constant thisind/prevind
- [ ] Possibly move optimized utf8 and utf16 support into StrUTF8 and StrUTF16 packages, to streamline main package
- [ ] Add in functionality from StringLiterals, but in such a way that the entity tables can be dynamically loaded, as well as the formatting support, and make it extensible, so that other extensions can be added.
- [ ] Support short strings
- [ ] Support storing type information at end of string, have single concrete type instead of UniStr.

**Comment by ScottPJones** [comment]
I haven't yet incorporated any sort of short string support yet into the `Str{...}` type, but have been supporting at-evalparse's ShortStrings.jl package (once I've learned enough from optimizing that, I'll attempt to apply that to the Str type, possibly adding a 5th parameter that specifies the underlying storage, currently `String`).

**Comment by jariji** [comment]
https://discourse.julialang.org/t/difference-between-shortstrings-jl-and-inlinestrings-jl/89127 says [InlineStrings.jl](https://github.com/JuliaStrings/InlineStrings.jl) is a replacement for ShortStrings.jl.

**Comment by hhaensel** [comment]
May I revive this old thread to hear what the current thoughts of the maintainers/contributors are about this package?

For me on Windows 11, Julia 1.9.3 the build of PCRE2.jl fails. This was quite surprising to me as the page reads like being a fundamental part of the Julia sphere.

With the latest master of PCRE2, PCRE2 builds fine and `Strs.jl` seems to work without problems.
Is this on the radar already or should I file a new issue about this?
